---
title: "Independent Project"
author: "Anahei Lara"
date: "2025-03-10"
output: pdf_document
---

# Introduction

*Borrelia burgdorferi* is a spirochete that causes Lyme disease, and it is the most prevalent vector-borne pathogen in the United States (Eisen *et al.* 2017). While the prevalence of the pathogen is widespread, the ecological and environmental factors influencing its dynamics differ significantly between the eastern and western regions of the United States. In the eastern United States, particularly in the primary vector is the black-legged tick, *Ixodes scapularis* and the white-tailed deer, *Odocoileus virginianus* is its main host (Gern *et al.* 2000). This region has long been recognized as a Lyme disease hotspot and has been studied extensively. Conversely, in the western United States, the western black-legged tick, *Ixodes pacificus* is the primary vector for *Borrelia burgdorferi* but the pathogen can also be found in two other *Ixodes* vectors: *Ixodes angustus* and *Ixodes spinipalpis* (Xu *et al.* 2019).*Ixodes pacificus* hosts are varied and consist of gray squirrels (*Sciurus griseus*), deer mice (*Peromyscus maniculatus*), and the Western fence lizard (*Sceloporus occidentalis*) among many other species (Castro and Wright 2007, Furman and Loomis 1984, McVicar *et al.* 2012). However, more research is needed on the western United States to determine *B. burgdorferi’s* genetic diversity which can illustrate the mechanism of how it's transmitted between vector and host.

There are at least 35 documented outer surface proteins with known roles (Pulzova and Bhide 2014). By observing four outer surface proteins, OspA, ospB, ospC, and  BBA64 (p35), we can determine how variations in these proteins effectively transmit the spirochete. Outer surface protein A and ospB are lipoproteins that have the ability to persist and settle in the tick’s midgut which is essential for the future transmission of the *Borrelia* spirochete (Caine *et al.* 2016). Additionally, ospC and p35 help the bacteria infect mammalian hosts after being transmitted through a tick bite that has been attached for at least 24 hours (Kenedy *et al.* 2012). In a tick that has not fed, ospA and ospB protein levels are elevated in the midgut while ospC and p35 levels are not present (Kenedy *et al.* 2012). In ticks that have fed on a host, ospC and p35 have elevated levels while ospA and ospB have low levels of expression (Tokarz *et al.* 2004). My research focuses on investigating these proteins genetic diversity to test for potential correlations in various tick and host species collected from the same geographic region in North Coastal California.

# Research Question

How does the genetic diversity of *Borrelia burgdorferi* outer surface proteins (OspA, OspB, OspC, and p35) correlate with the diversity of tick and host species, and what implications does this have for pathogen transmission and persistence?

# Aims

1. Characterize the genetic diversity of OspA and OspB in *Borrelia burgdorferi* across various *Ixodes* tick species to determine their role in tick-borne persistence.  

2. Analyze the genetic variation of OspC and p35 in *B. burgdorferi*  collected from different host species to assess their influence on host immune evasion and transmission dynamics.  
